.Dd $Mdocdate$
.Dt MIDIMAP.MAP 5
.Os
.Sh NAME
.Nm midimap.map
.Nd
.Xr midimap 1 map format
.Sh DESCRIPTION
This manual describes the
.Nm
format, used by
.Xr midimap 1
to determine which MIDI events map to which actions.
.Pp
A
.Nm
file is a comma separated values (RFC 4180) file with two fields per record (line).
Each record consists of one MATCHER field followed by one or more ACTION fields.
.Pp
The MATCHER field is an expression which either match or do not match a MIDI event.
The syntax of the MATCHER field is described in the MATCHER SYNTAX section.
.Pp
The ACTION fields, are expressions which describe actions such as simulating a keypress or running a command, to be performed.
There may be an arbitrary number of ACTION fields per record.
The syntax of the ACTION field is described in the ACTION SYNTAX section.
.Pp
If the MATCHER expression of a record matches an incoming MIDI event, all the ACTIONs of the record are performed.
.Sh MATCHER SYNTAX
To be specified.
.Sh ACTION SYNTAX
To be specified.
.Sh EXAMPLES
To be written.
.Sh SEE ALSO
.Xr midimap 1
.Pp
\" Alternatively the official name of the document(Common Format and MIME Type for Comma-Separated Values (CSV) Files) could be used.
.Lk https://tools.ietf.org/html/rfc4180 "RFC 4180" ,
.Lk https://github.com/fossegrim/midimap
.Sh AUTHORS
.An Olav Fosse Aq Mt mail@olavfosse.no
